### PR TITLE
Update InsecureContentSecurityPolicy.bcheck

### PR DESCRIPTION
**Pull request by LabMC**
- Updated Insecure Content-Security-Policy file.
  - Added measures to reduce false positives.
  - Added tests for missing default-src, script-src, object-src, object-src, & require-trusted-types-for directives.
  - Added tests for usage of "http:", "data:", & non-specified https:; URL paths.
  - Added some additional recommendations regarding suggestions/remediation.

- I was able to successfully QA, confirm the plugin is working on my side & resolve what issues I found.
  - Let me know if these updates appear noncomplaint or erronous for some reason.

### BCheck Contributions

* [x] BCheck compiles and executes as expected
* [x] BCheck contains appropriate metadata (name, version, author, description and appropriate tags)
* [x] Only .bcheck files have been added or modified
* [x] BCheck is in the appropriate folder
* [x] PR contains single or limited number of BChecks (Multiple PRs are preferred)
* [x] BCheck attempts to minimize false positives

### CODE REVIEW

**Review by PortSwiggerWiener — APPROVED** [review]
Thanks for your submission. 

Looks good. 👍

**Review by Michelle-PortSwigger — APPROVED** [review]
Looks good

**Comment by michael-eaton-portswigger** [comment]
@LabMC As a contributor to our GitHub repository, we would like to invite you to our closed Discord community.

It is a place where passionate Burp users, including people who directly work on building and developing Burp here at PortSwigger, can talk about the tooling and web security in general.

If you would like to join, please email us at [support@portswigger.net](mailto:support@portswigger.net) and we will send over an invite link.

Thank you!

**Comment by LabMC** [comment]
Hello,

Count me in! 👍

**Pull request merged**
