### PR TITLE
Create php-8.1.0-dev-backdoor.bcheck

### PR DESCRIPTION
**Pull request by r3nt0n**
### BCheck Contributions

This Bcheck attempts to detect servers running PHP 8.1.0-dev, which was released with a backdoor allowing Code Injection.

* [x] BCheck compiles and executes as expected
* [x] BCheck contains appropriate metadata (name, version, author, description and appropriate tags)
* [x] Only .bcheck files have been added or modified
* [x] BCheck is in the appropriate folder
* [x] PR contains single or limited number of BChecks (Multiple PRs are preferred)
* [x] BCheck attempts to minimize false positives

### CODE REVIEW

**Review by PortSwiggerWiener — COMMENTED** [review]
Many thanks for your submission.

It looks good. Only suggestion would be to check for the fingerprint (1787589) in the base response to eliminate potential false positives.

**Comment by r3nt0n** [comment]
Thanks for the feedback!

The expected output used as a fingerprint includes the "int()" around the number, I thought that the chances to find that specific string were low enough.

Ideally, we would use a loop until find some calculation result which doesn't appear in the base response, and then send the request with the associated payload, but I'm not sure if this could be accomplished with the current Bcheck possibilities.

Maybe increasing the length of the expected output (like 13333337*13333337) could reduce false positives rate to something acceptable?

**Comment by PortSwiggerWiener** [comment]
No that's a fair point. I'll approve it now.

Thanks again for the submission.

**Review by PortSwiggerWiener — APPROVED** [review]

**Review by Hannah-PortSwigger — APPROVED** [review]
Looks good! 👍

**Pull request merged**
