### PR TITLE
Added CRLFInjection.bcheck

### PR DESCRIPTION
**Pull request by 0xGodson**
BCheck rule to find CRLF Injections.

### CODE REVIEW

**Review by A-J-C — APPROVED** [review]

**Review by PortSwiggerWiener — APPROVED** [review]
👍

**Comment by michael-eaton-portswigger** [comment]
@0xGodson As a contributor to our GitHub repository, we would like to invite you to our closed Discord community.

It is a place where passionate Burp users, including people who directly work on building and developing Burp here at PortSwigger, can talk about the tooling and web security in general.

If you would like to join, please email us at [support@portswigger.net](mailto:support@portswigger.net) and we will send over an invite link.

Thank you!

**Comment by 0xGodson** [comment]
Hi @michael-eaton-portswigger , 

I am interested in joining the discord.

My email: 0xgodson@gmail.com

I will shortly send an email to support@portswigger.net with my discord username.

Thank you!

**Comment by Hannah-PortSwigger** [comment]
Thanks, we've got your email!

**Pull request merged**
