### PR TITLE
Path confusion check added

### PR DESCRIPTION
**Pull request by tr3harder**
Check for misconfiguration while routing .css, .js, .png files. If it exists attacker can try to chain it using cache deception.
More detailed https://book.hacktricks.xyz/pentesting-web/cache-deception#cache-deception
Such type of bug was found on OpenAI lately.

Another requirement to find this bug is to have caching service. Because it can be very various user should do this step manually. 

I also have a question:
Is it possible to make check only if base response was 200? If so, can you kindly modify my bcheck

### CODE REVIEW

**Review by PortSwiggerWiener — COMMENTED** [review]
👍

**Comment by A-J-C** [comment]
"Is it possible to make check only if base response was 200? If so, can you kindly modify my bcheck" -> Yes this would be possible. 

You just need to add an `if {base.response.status} is '200' then` line between your `given request` and `send request`. 

I'll wait to approve this PR until that change is made.

**Comment by tr3harder** [comment]
@A-J-C Hi Alex,
I have tried and it doesnt work for me. Attach screenshot

image

**Comment by PortSwiggerWiener** [comment]
try:  `if {base.response.status_code} is "200" then`

**Comment by tr3harder** [comment]
@PortSwiggerWiener thanks. updated
i think i have tried it but nevermind:)

**Review by olliewuk — APPROVED** [review]

**Comment by michael-eaton-portswigger** [comment]
@tr3harder As a contributor to our GitHub repository, we would like to invite you to our closed Discord community.

It is a place where passionate Burp users, including people who directly work on building and developing Burp here at PortSwigger, can talk about the tooling and web security in general.

If you would like to join, please email us at [support@portswigger.net](mailto:support@portswigger.net) and we will send over an invite link.

Thank you!

**Pull request merged**
