### PR TITLE
Add detection of SameSite disabled

### PR DESCRIPTION
**Pull request by righettod**
Hello,

This PR propose a script to detect when a cookie disable the **SameSite** protection by setting the value to `None`.

The objective of the script is to raise a information notice to allow to investigate to see if an CSRF attack can be used due to this settings.

Thanks you very much in advance for your feedback 😃

### CODE REVIEW

**Comment by righettod** [comment]
Hi @PortSwiggerWiener, 

Thanks a lot for your feedback, I applied all your feedback.

Feel free to reach if I missed something 😃

**Review by PortSwiggerWiener — APPROVED** [review]
Thanks for the changes! 👍

**Comment by righettod** [comment]
You are welcome, thanks for the review.

**Review by Michelle-PortSwigger — APPROVED** [review]
All looks good to me too

**Comment by righettod** [comment]
Thank you very much 😃

**Comment by michael-eaton-portswigger** [comment]
@righettod As a contributor to our GitHub repository, we would like to invite you to our closed Discord community.

It is a place where passionate Burp users, including people who directly work on building and developing Burp here at PortSwigger, can talk about the tooling and web security in general.

If you would like to join, please email us at [support@portswigger.net](mailto:support@portswigger.net) and we will send over an invite link.

Thank you!

**Pull request merged**
