### PR TITLE
R3dg33k patch 1

### PR DESCRIPTION
**Pull request by r3dg33k**

### CODE REVIEW

**Review by PortSwiggerWiener — COMMENTED** [review]
Looks good. Can you make the indentation consistent please ('tags' and 'end if')? You could replace the 'run for each' with a 'define' as you only have a single value. It would also be more efficient to check the status code first.

**Comment by r3dg33k** [comment]
done. thanks.

**Review by PortSwiggerWiener — APPROVED** [review]
👍

**Review by A-J-C — APPROVED** [review]

**Comment by michael-eaton-portswigger** [comment]
@r3dg33k As a contributor to our GitHub repository, we would like to invite you to our closed Discord community.

It is a place where passionate Burp users, including people who directly work on building and developing Burp here at PortSwigger, can talk about the tooling and web security in general.

If you would like to join, please email us at [support@portswigger.net](mailto:support@portswigger.net) and we will send over an invite link.

Thank you!

**Pull request merged**
